version: '3.7'

services:
  hl_node_nusspaumer:
    build: .
    command: bash -c "npm start"
    container_name: hotel_location_node_nusspaumer_container
    volumes:
      - .:/hotel-location
    ports:
      - "3048:3000"
    networks:
      - nusspaumer-network
    depends_on:
      - hl_db_nusspaumer

  hl_db_nusspaumer:
    image: postgres:11.5
    container_name: hotel_location_db_nusspaumer_container
    ports:
      - "5448:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hotel_location
    networks:
      - nusspaumer-network

networks:
  nusspaumer-network:
    name: nusspaumer-network
    driver: "bridge"
volumes:
  data:
    driver: "local"